import math

from src.dag.extractor import DAG
from src.serialize.strategies import serialize_dag


class ContextAssembler:
    """
    Assembles the two-tier context injected into every LLM request.

    Tier 1 (~200 tokens, always present):
        Global summary of the entire graph. Generated by compression
        Engine 5 (M8). Cached in memory, loaded from meta table at
        startup. Changes at most once per hour. Before Engine 5 has run
        (graph too sparse, < 15 nodes), Tier 1 is an empty string.

    Tier 2 (~800 tokens, dynamic per query):
        Output of serialize_dag(). Changes every turn.

    Total budget: ~1000 tokens (200 + 800).
    """

    def __init__(
        self,
        tier1_budget_tokens: int = 200,
        tier2_budget_tokens: int = 800,
        chars_per_token: float = 3.5,
    ):
        self._tier1_budget = tier1_budget_tokens
        self._tier2_budget = tier2_budget_tokens
        self._chars_per_token = chars_per_token
        self._global_summary: str = ""  # populated by update_global_summary()

    def update_global_summary(self, summary: str) -> None:
        """
        Called at startup (loaded from meta table) and by compression
        Engine 5 (M8) whenever a new summary is generated.
        Enforces the Tier 1 token budget on the stored summary.
        """
        max_chars = math.ceil(self._tier1_budget * self._chars_per_token)
        self._global_summary = (summary or "")[:max_chars]

    def assemble(self, dag: DAG) -> str:
        """
        Build the full context string to inject into the LLM prompt.

        Structure:
            [GLOBAL CONTEXT]
            {tier1_global_summary}          <- omitted if empty

            {tier2_dag_context}             <- serialize_dag() output

        serialize_dag() already enforces its own Tier 2 budget using this
        assembler's configured chars_per_token/tier2_budget, so no
        re-truncation happens here - it is the single source of truth for
        Tier 2 sizing (mirrors M5's _estimate_tokens() single-source-of-
        truth pattern).

        If global_summary is empty (early sessions, no Engine 5 run yet):
            Return only the Tier 2 content.
        """
        tier2 = serialize_dag(
            dag,
            chars_per_token=self._chars_per_token,
            tier2_budget=self._tier2_budget,
        )

        if not self._global_summary:
            return tier2

        return f"[GLOBAL CONTEXT]\n{self._global_summary}\n\n{tier2}"

    def total_tokens_within_budget(self, assembled: str) -> bool:
        """
        Check whether assembled context fits within total budget.
        Uses same chars_per_token approximation as the rest of the pipeline.
        """
        estimated = len(assembled) / self._chars_per_token
        return estimated <= (self._tier1_budget + self._tier2_budget)